In [1]:
!pip install faker

Requirement already satisfied: faker in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (40.11.0)
Requirement already satisfied: tzdata in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from faker) (2025.2)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
#faker generates realistic names,emails,phones,addresses,dates etc

In [3]:
from faker import Faker
import pandas as pd
import random

In [6]:
fake=Faker()
data=[]
for _ in range(1000):
    data.append({
        "name":fake.name(),
        "age":random.randint(18,65),
        "email":fake.email(),
        "salary":random.randint(30000,120000)
    })
df=pd.DataFrame(data)

In [7]:
df.head()

              name  age                       email  salary
0       Mary Blair   30          tscott@example.com   70775
1   John Fernandez   61         frank11@example.net   80327
2  Nicholas Vaughn   29  autumnanderson@example.net   71509
3    Kellie Miller   35          ofloyd@example.com   48845
4     Vincent Rich   19       mikayla44@example.net   61335

In [8]:
df.tail()

                   name  age                     email  salary
995      Emily Mcknight   52    reesekevin@example.net   80270
996    Mr. Andrew Haley   48       derek26@example.net   46525
997  Nicholas Armstrong   26  kathrynjames@example.net   49362
998           Kim Pitts   49     smckenzie@example.net   75591
999        Tina Hartman   21  pattersonana@example.net   91607

In [9]:
#Using Numpy
import numpy as np
import pandas as pd
n=5000
df=pd.DataFrame({
    "age":np.random.normal(35,10,n).astype(int),
    "income":np.random.normal(60000,15000,n),
    "experience":np.random.randint(0,25,n)
})

In [10]:
df.head()

   age         income  experience
0   27   83313.305622          15
1   37   72247.895095          22
2   34  111069.578509          16
3   34   52374.186519           0
4   23   64773.715325          21

In [13]:
#Scikit_learn
from sklearn.datasets import make_classification
X,y=make_classification(
    n_samples=1000,
    n_features=20,
    n_informative=10,
    random_state=42
)

In [15]:
X.shape

(1000, 20)

In [16]:
y.shape

(1000,)

In [18]:
!pip install sdv

Collecting sdv
  Downloading sdv-1.37.3-py3-none-any.whl.metadata (14 kB)
Collecting boto3<2.0.0,>=1.28 (from sdv)
  Downloading boto3-1.43.45-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<2.0.0,>=1.31 (from sdv)
  Downloading botocore-1.43.45-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: cloudpickle>=2.1.0 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from sdv) (3.1.2)
Collecting graphviz>=0.13.2 (from sdv)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.24.0 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from sdv) (1.26.4)
Collecting pandas<3,>=1.5.0 (from sdv)
  Downloading pandas-2.3.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: tqdm>=4.29 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from sdv) (4.67.1)
Collecting copulas>=0.12.1 (from sdv)
  Downloading copulas-0.14.1-py3-none-any.whl.metadata (9.7 kB)
Collecting ctgan>=0.11.1 (from sdv)
  Downloading ctgan-0.12.1-py3-none-any.whl.metadata (10 kB)
Collecting deepecho>=0.7.0 (from sdv)
  Downloading deepecho-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting rdt>=1.18.2 (from sdv)
  Downloading rdt-1.21.0-py3-none-any.whl.metadata (11 kB)
Collecting sdmetrics>=0.28.0 (from sdv)
  Downloading sdmetrics-0.28.0-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: platformdirs>=4.0 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from sdv) (4.3.8)
Requirement already satisfied: pyyaml>=6.0.1 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from sdv) (6.0.3)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0.0,>=1.28->sdv)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3<2.0.0,>=1.28->sdv)
  Downloading s3transfer-0.19.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from botocore<2.0.0,>=1.31->sdv) (2.4.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from pandas<3,>=1.5.0->sdv) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from pandas<3,>=1.5.0->sdv) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.17.0)
Requirement already satisfied: plotly>=5.10.0 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from copulas>=0.12.1->sdv) (5.24.1)
Requirement already satisfied: scipy>=1.9.2 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from copulas>=0.12.1->sdv) (1.15.2)
Requirement already satisfied: torch>=2.0.0 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from ctgan>=0.11.1->sdv) (2.8.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\shraddha\appdata\roaming\python\python311\site-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (9.1.2)
Requirement already satisfied: packaging in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from plotly>=5.10.0->copulas>=0.12.1->sdv) (25.0)
Requirement already satisfied: scikit-learn>=1.1.3 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from rdt>=1.18.2->sdv) (1.9.0)
Requirement already satisfied: Faker!=37.11.0,>=17 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from rdt>=1.18.2->sdv) (40.11.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.1.3->rdt>=1.18.2->sdv) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.1.3->rdt>=1.18.2->sdv) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.1.3->rdt>=1.18.2->sdv) (3.6.0)
Requirement already satisfied: filelock in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.1->sdv) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.1->sdv) (4.14.1)
Requirement already satisfied: sympy>=1.13.3 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.1->sdv) (1.14.0)
Requirement already satisfied: networkx in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.1->sdv) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.1->sdv) (3.1.6)
Requirement already satisfied: fsspec in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from torch>=2.0.0->ctgan>=0.11.1->sdv) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->ctgan>=0.11.1->sdv) (1.3.0)
Requirement already satisfied: colorama in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from tqdm>=4.29->sdv) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shraddha\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch>=2.0.0->ctgan>=0.11.1->sdv) (2.1.5)
Downloading sdv-1.37.3-py3-none-any.whl (207 kB)
Downloading boto3-1.43.45-py3-none-any.whl (140 kB)
Downloading botocore-1.43.45-py3-none-any.whl (15.4 MB)
   ---------------------------------------- 0.0/15.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.4 MB ? eta -:--:--
    --------------------------------------- 0.3/15.4 MB ? eta -:--:--
    --------------------------------------- 0.3/15.4 MB ? eta -:--:--
    --------------------------------------- 0.3/15.4 MB ? eta -:--:--
    --------------------------------------- 0.3/15.4 MB ? eta -:--:--
    --------------------------------------- 0.3/15.4 MB ? eta -:--:--
    --------------------------------------- 0.3/15.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/15.4 MB 186.4 kB/s eta 0:01:20
   - -------------------------------------- 0.5/15.4 MB 186.4 kB/s eta 0:01:20
   - -------------------------------------- 0.5/15.4 MB 186.4 kB/s eta 0:01:20
   - -------------------------------------- 0.5/15.4 MB 186.4 kB/s eta 0:01:20
   - -------------------------------------- 0.5/15.4 MB 186.4 kB/s eta 0:01:20
   - -------------------------------------- 0.5/15.4 MB 186.4 kB/s eta 0:01:20
   -- ------------------------------------- 0.8/15.4 MB 209.7 kB/s eta 0:01:10
   -- ------------------------------------- 0.8/15.4 MB 209.7 kB/s eta 0:01:10
   -- ------------------------------------- 0.8/15.4 MB 209.7 kB/s eta 0:01:10
   -- ------------------------------------- 0.8/15.4 MB 209.7 kB/s eta 0:01:10
   -- ------------------------------------- 0.8/15.4 MB 209.7 kB/s eta 0:01:10
   -- ------------------------------------- 0.8/15.4 MB 209.7 kB/s eta 0:01:10
   -- ------------------------------------- 1.0/15.4 MB 204.6 kB/s eta 0:01:11
   -- ------------------------------------- 1.0/15.4 MB 204.6 kB/s eta 0:01:11
   -- ------------------------------------- 1.0/15.4 MB 204.6 kB/s eta 0:01:11
   -- ------------------------------------- 1.0/15.4 MB 204.6 kB/s eta 0:01:11
   -- ------------------------------------- 1.0/15.4 MB 204.6 kB/s eta 0:01:11
   --- ------------------------------------ 1.3/15.4 MB 210.4 kB/s eta 0:01:07
   --- ------------------------------------ 1.3/15.4 MB 210.4 kB/s eta 0:01:07
   --- ------------------------------------ 1.3/15.4 MB 210.4 kB/s eta 0:01:07
   --- ------------------------------------ 1.3/15.4 MB 210.4 kB/s eta 0:01:07
   --- ------------------------------------ 1.3/15.4 MB 210.4 kB/s eta 0:01:07
   ---- ----------------------------------- 1.6/15.4 MB 221.9 kB/s eta 0:01:03
   ---- ----------------------------------- 1.6/15.4 MB 221.9 kB/s eta 0:01:03
   ---- ----------------------------------- 1.6/15.4 MB 221.9 kB/s eta 0:01:03
   ---- ----------------------------------- 1.6/15.4 MB 221.9 kB/s eta 0:01:03
   ---- ----------------------------------- 1.6/15.4 MB 221.9 kB/s eta 0:01:03
   ---- ----------------------------------- 1.8/15.4 MB 224.2 kB/s eta 0:01:01
   ---- ----------------------------------- 1.8/15.4 MB 224.2 kB/s eta 0:01:01
   ---- ----------------------------------- 1.8/15.4 MB 224.2 kB/s eta 0:01:01
   ---- ----------------------------------- 1.8/15.4 MB 224.2 kB/s eta 0:01:01
   ---- ----------------------------------- 1.8/15.4 MB 224.2 kB/s eta 0:01:01
   ----- ---------------------------------- 2.1/15.4 MB 229.8 kB/s eta 0:00:58
   ----- ---------------------------------- 2.1/15.4 MB 229.8 kB/s eta 0:00:58
   ----- ---------------------------------- 2.1/15.4 MB 229.8 kB/s eta 0:00:58
   ----- ---------------------------------- 2.1/15.4 MB 229.8 kB/s eta 0:00:58
   ------ --------------------------------- 2.4/15.4 MB 236.7 kB/s eta 0:00:55
   ------ --------------------------------- 2.4/15.4 MB 236.7 kB/s eta 0:00:55
   ------ --------------------------------- 2.4/15.4 MB 236.7 kB/s eta 0:00:55
   ------ --------------------------------- 2.6/15.4 MB 247.1 kB/s eta 0:00:52
   ------ --------------------------------- 2.6/15.4 MB 247.1 kB/s eta 0:00:52
   ------ --------------------------------- 2.6/15.4 MB 247.1 kB/s eta 0:00:52
   ------- -------------------------------- 2.9/15.4 MB 260.5 kB/s eta 0:00:48
   ------- -------------------------------- 2.9/15.4 MB 260.5 kB/s eta 0:00:48
   -------- ------------------------------- 3.1/15.4 MB 275.9 kB/s eta 0:00:45
   -------- ------------------------------- 3.4/15.4 MB 291.8 kB/s eta 0:00:42
   -------- ------------------------------- 3.4/15.4 MB 291.8 kB/s eta 0:00:42
   -------- ------------------------------- 3.4/15.4 MB 291.8 kB/s eta 0:00:42
   --------- ------------------------------ 3.7/15.4 MB 301.3 kB/s eta 0:00:39
   --------- ------------------------------ 3.7/15.4 MB 301.3 kB/s eta 0:00:39
   --------- ------------------------------ 3.7/15.4 MB 301.3 kB/s eta 0:00:39
   --------- ------------------------------ 3.7/15.4 MB 301.3 kB/s eta 0:00:39
   ---------- ----------------------------- 3.9/15.4 MB 304.3 kB/s eta 0:00:38
   ---------- ----------------------------- 3.9/15.4 MB 304.3 kB/s eta 0:00:38
   ---------- ----------------------------- 3.9/15.4 MB 304.3 kB/s eta 0:00:38
   ---------- ----------------------------- 3.9/15.4 MB 304.3 kB/s eta 0:00:38
   ---------- ----------------------------- 3.9/15.4 MB 304.3 kB/s eta 0:00:38
   ---------- ----------------------------- 4.2/15.4 MB 297.5 kB/s eta 0:00:38
   ---------- ----------------------------- 4.2/15.4 MB 297.5 kB/s eta 0:00:38
   ---------- ----------------------------- 4.2/15.4 MB 297.5 kB/s eta 0:00:38
   ---------- ----------------------------- 4.2/15.4 MB 297.5 kB/s eta 0:00:38
   ---------- ----------------------------- 4.2/15.4 MB 297.5 kB/s eta 0:00:38
   ---------- ----------------------------- 4.2/15.4 MB 297.5 kB/s eta 0:00:38
   ----------- ---------------------------- 4.5/15.4 MB 291.8 kB/s eta 0:00:38
   ----------- ---------------------------- 4.5/15.4 MB 291.8 kB/s eta 0:00:38
   ----------- ---------------------------- 4.5/15.4 MB 291.8 kB/s eta 0:00:38
   ----------- ---------------------------- 4.5/15.4 MB 291.8 kB/s eta 0:00:38
   ----------- ---------------------------- 4.5/15.4 MB 291.8 kB/s eta 0:00:38
   ------------ --------------------------- 4.7/15.4 MB 289.0 kB/s eta 0:00:37
   ------------ --------------------------- 4.7/15.4 MB 289.0 kB/s eta 0:00:37
   ------------ --------------------------- 4.7/15.4 MB 289.0 kB/s eta 0:00:37
   ------------ --------------------------- 4.7/15.4 MB 289.0 kB/s eta 0:00:37
   ------------ --------------------------- 4.7/15.4 MB 289.0 kB/s eta 0:00:37
   ------------ --------------------------- 4.7/15.4 MB 289.0 kB/s eta 0:00:37
   ------------ --------------------------- 4.7/15.4 MB 289.0 kB/s eta 0:00:37
   ------------ --------------------------- 5.0/15.4 MB 279.9 kB/s eta 0:00:38
   ------------ --------------------------- 5.0/15.4 MB 279.9 kB/s eta 0:00:38
   ------------ --------------------------- 5.0/15.4 MB 279.9 kB/s eta 0:00:38
   ------------ --------------------------- 5.0/15.4 MB 279.9 kB/s eta 0:00:38
   ------------ --------------------------- 5.0/15.4 MB 279.9 kB/s eta 0:00:38
   ------------ --------------------------- 5.0/15.4 MB 279.9 kB/s eta 0:00:38
   ------------ --------------------------- 5.0/15.4 MB 279.9 kB/s eta 0:00:38
   ------------ --------------------------- 5.0/15.4 MB 279.9 kB/s eta 0:00:38
   ------------- -------------------------- 5.2/15.4 MB 266.7 kB/s eta 0:00:38
   ------------- -------------------------- 5.2/15.4 MB 266.7 kB/s eta 0:00:38
   ------------- -------------------------- 5.2/15.4 MB 266.7 kB/s eta 0:00:38
   ------------- -------------------------- 5.2/15.4 MB 266.7 kB/s eta 0:00:38
   -------------- ------------------------- 5.5/15.4 MB 268.4 kB/s eta 0:00:37
   -------------- ------------------------- 5.5/15.4 MB 268.4 kB/s eta 0:00:37
   -------------- ------------------------- 5.5/15.4 MB 268.4 kB/s eta 0:00:37
   -------------- ------------------------- 5.5/15.4 MB 268.4 kB/s eta 0:00:37
   --------------- ------------------------ 5.8/15.4 MB 270.8 kB/s eta 0:00:36
   --------------- ------------------------ 5.8/15.4 MB 270.8 kB/s eta 0:00:36
   --------------- ------------------------ 5.8/15.4 MB 270.8 kB/s eta 0:00:36
   --------------- ------------------------ 5.8/15.4 MB 270.8 kB/s eta 0:00:36
   --------------- ------------------------ 6.0/15.4 MB 271.6 kB/s eta 0:00:35
   --------------- ------------------------ 6.0/15.4 MB 271.6 kB/s eta 0:00:35
   --------------- ------------------------ 6.0/15.4 MB 271.6 kB/s eta 0:00:35
   --------------- ------------------------ 6.0/15.4 MB 271.6 kB/s eta 0:00:35
   --------------- ------------------------ 6.0/15.4 MB 271.6 kB/s eta 0:00:35
   ---------------- ----------------------- 6.3/15.4 MB 271.2 kB/s eta 0:00:34
   ---------------- ----------------------- 6.3/15.4 MB 271.2 kB/s eta 0:00:34
   ---------------- ----------------------- 6.3/15.4 MB 271.2 kB/s eta 0:00:34
   ---------------- ----------------------- 6.3/15.4 MB 271.2 kB/s eta 0:00:34
   ---------------- ----------------------- 6.3/15.4 MB 271.2 kB/s eta 0:00:34
   ---------------- ----------------------- 6.3/15.4 MB 271.2 kB/s eta 0:00:34
   ----------------- ---------------------- 6.6/15.4 MB 268.4 kB/s eta 0:00:33
   ----------------- ---------------------- 6.6/15.4 MB 268.4 kB/s eta 0:00:33
   ----------------- ---------------------- 6.6/15.4 MB 268.4 kB/s eta 0:00:33
   ----------------- ---------------------- 6.6/15.4 MB 268.4 kB/s eta 0:00:33
   ----------------- ---------------------- 6.6/15.4 MB 268.4 kB/s eta 0:00:33
   ----------------- ---------------------- 6.6/15.4 MB 268.4 kB/s eta 0:00:33
   ----------------- ---------------------- 6.6/15.4 MB 268.4 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ----------------- ---------------------- 6.8/15.4 MB 264.0 kB/s eta 0:00:33
   ------------------- -------------------- 7.3/15.4 MB 253.9 kB/s eta 0:00:32
   ------------------- -------------------- 7.3/15.4 MB 253.9 kB/s eta 0:00:32
   ------------------- -------------------- 7.3/15.4 MB 253.9 kB/s eta 0:00:32
   ------------------- -------------------- 7.3/15.4 MB 253.9 kB/s eta 0:00:32
   ------------------- -------------------- 7.3/15.4 MB 253.9 kB/s eta 0:00:32
   ------------------- -------------------- 7.3/15.4 MB 253.9 kB/s eta 0:00:32
   ------------------- -------------------- 7.6/15.4 MB 252.3 kB/s eta 0:00:31
   ------------------- -------------------- 7.6/15.4 MB 252.3 kB/s eta 0:00:31
   ------------------- -------------------- 7.6/15.4 MB 252.3 kB/s eta 0:00:31
   ------------------- -------------------- 7.6/15.4 MB 252.3 kB/s eta 0:00:31
   ------------------- -------------------- 7.6/15.4 MB 252.3 kB/s eta 0:00:31
   ------------------- -------------------- 7.6/15.4 MB 252.3 kB/s eta 0:00:31
   ------------------- -------------------- 7.6/15.4 MB 252.3 kB/s eta 0:00:31
   ------------------- -------------------- 7.6/15.4 MB 252.3 kB/s eta 0:00:31
   -------------------- ------------------- 7.9/15.4 MB 250.4 kB/s eta 0:00:30
   -------------------- ------------------- 7.9/15.4 MB 250.4 kB/s eta 0:00:30
   -------------------- ------------------- 7.9/15.4 MB 250.4 kB/s eta 0:00:30
   -------------------- ------------------- 7.9/15.4 MB 250.4 kB/s eta 0:00:30
   -------------------- ------------------- 7.9/15.4 MB 250.4 kB/s eta 0:00:30
   -------------------- ------------------- 7.9/15.4 MB 250.4 kB/s eta 0:00:30
   -------------------- ------------------- 7.9/15.4 MB 250.4 kB/s eta 0:00:30
   --------------------- ------------------ 8.1/15.4 MB 246.5 kB/s eta 0:00:30
   --------------------- ------------------ 8.1/15.4 MB 246.5 kB/s eta 0:00:30
   --------------------- ------------------ 8.1/15.4 MB 246.5 kB/s eta 0:00:30
   --------------------- ------------------ 8.1/15.4 MB 246.5 kB/s eta 0:00:30
   --------------------- ------------------ 8.1/15.4 MB 246.5 kB/s eta 0:00:30
   --------------------- ------------------ 8.1/15.4 MB 246.5 kB/s eta 0:00:30
   --------------------- ------------------ 8.1/15.4 MB 246.5 kB/s eta 0:00:30
   --------------------- ------------------ 8.4/15.4 MB 247.0 kB/s eta 0:00:29
   --------------------- ------------------ 8.4/15.4 MB 247.0 kB/s eta 0:00:29
   --------------------- ------------------ 8.4/15.4 MB 247.0 kB/s eta 0:00:29
   --------------------- ------------------ 8.4/15.4 MB 247.0 kB/s eta 0:00:29
   ---------------------- ----------------- 8.7/15.4 MB 247.8 kB/s eta 0:00:28
   ---------------------- ----------------- 8.7/15.4 MB 247.8 kB/s eta 0:00:28

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Shraddha\AppData\Local\Programs\Python\Python311\Lib\site-packages\~andas.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Shraddha\AppData\Local\Programs\Python\Python311\Lib\site-packages\~andas'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.46.1 requires cachetools<7,>=4.0, but you have cachetools 7.1.4 which is incompatible.
pandas-profiling 3.2.0 requires joblib~=1.1.0, but you have joblib 1.5.3 which is incompatible.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.8.1 which is incompatible.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
import pandas as pd

real_df = pd.DataFrame({
    "age": [25, 32, 45, 29, 38],
    "salary": [50000, 75000, 120000, 65000, 90000],
    "department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "experience": [2, 7, 15, 4, 10]
})

print(real_df)

   age  salary department  experience
0   25   50000         HR           2
1   32   75000         IT           7
2   45  120000    Finance          15
3   29   65000         IT           4
4   38   90000  Marketing          10

In [23]:
from sdv.single_table import CTGANSynthesizer
from sdv.metadata import Metadata
metadata=Metadata.detect_from_dataframe(real_df)
synthesizer=CTGANSynthesizer(metadata)
synthesizer.fit(real_df)
synthetic_df=synthesizer.sample(5000)

C:\Users\Shraddha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sdv\single_table\base.py:139: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

In [24]:
#SDV learns the relationship between columns(eg age salary etc) aand generate realistic new rows

In [25]:
synthetic_df.head()

   age  salary department  experience
0   37   50000    Finance          10
1   26   61936         IT          12
2   25   50000         IT           4
3   26   50000    Finance           6
4   34   77257    Finance          10

In [29]:
from ctgan import CTGAN

ctgan = CTGAN()

categorical_columns = ["department"]  # replace with your string columns

ctgan.fit(real_df, discrete_columns=categorical_columns)
synthetic=ctgan.sample(1000)

In [32]:
synthetic.head()

   age  salary department  experience
0   16  127269  Marketing          15
1   40   84005  Marketing           2
2   42   70107         IT          17
3   28   41535         IT          -2
4   25  115620    Finance          20

In [27]:
real_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         5 non-null      int64
 1   salary      5 non-null      int64
 2   department  5 non-null      str
 3   experience  5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 314.0 bytes

In [30]:
#GAN based models specifically designed for tabular data